Feature/Read data from Terabee TOF sensor
QUB-ASL/bzzz pull request #156
Opened 2023-11-14 15:44 UTC by Yuanbwcx

## Main Changes

Evo_single_point_display_range_py3.py can be used to detect and read data from Terabee TOF sensor

## Tests

This has been tested and works good at 15m and 60m one.

2023-11-15 13:15 UTC, alphaville commented on raspberry/bzzz/sensors/TeraBee_Evo_time_of_flight_sensor/Evo_single_point_display_range_py3.py
> +def openEvo(portname):
Function names should be snake-case (see [here](https://github.com/QUB-ASL/bzzz/blob/main/CONTRIBUTING.md#32-python))

2023-11-15 14:06 UTC, alphaville commented on raspberry/bzzz/sensors/TeraBee_Evo_time_of_flight_sensor/Evo_single_point_display_range_py3.py
> +#!/usr/bin/env python3
This code, taken from the sample codes of Evo, is in the form of a script. For us to be able to use it in this project we need to make it into a class. I would suggest the following structure:

```python
class EvoSensor:

    def __init__(self, port, baud=115200):
       # initialise Evo sensor

    def read(self):
        # returns reading from sensor
```

2023-11-15 14:07 UTC, alphaville requested changes
@jamie-54 can you help Siyuan with this?

2023-11-15 14:38 UTC, jamie-54 commented
> @jamie-54 can you help Siyuan with this?

yea

2023-11-22 10:40 UTC, alphaville commented
@Yuanbwcx @jamie-54 How is it going guys? Has this stagnated?

2023-11-22 20:34 UTC, alphaville commented
In this PR we should probably do the save as in #137.

2023-11-28 16:59 UTC, closed without merging

2023-11-29 14:56 UTC, alphaville commented
@jamie-54 Why was this PR closed?