Integration of individual components
QUB-ASL/bzzz pull request #16
Opened 2023-04-19 19:57 UTC by jamie-54

## Main Changes

- new quaternion class implementation
- first version of controller
- getter for angular velocity in AHRS
- `main.cpp`: experimental integration

## Associated Issues

- Closes #13

2023-04-19 23:20 UTC, alphaville reviewed
Jamie, I made a few edits directly to this PR. Let's discuss tomorrow morning.

2023-04-20 07:22 UTC, jamie-54 commented
> Jamie, I made a few edits directly to this PR. Let's discuss tomorrow morning.

Ok I'm in uni on 10th floor now

2023-04-30 18:48 UTC, alphaville reviewed
Overall it looks good. Just have a look at #25 first.

2023-05-01 09:46 UTC, jamie-54 commented
Hi all, flight-zero is now working correctly like last Friday and the correct code is now pushed to this branch.
@alphaville I Think we might be better to merge this working code into dev first and then we can sort issue https://github.com/QUB-ASL/bzzz/pull/25. Since I had to go back to a previous commit there is a few other parameters and things need to be defined again which we can sort with along with https://github.com/QUB-ASL/bzzz/pull/25. Thanks

2023-05-01 13:36 UTC, jamie-54 commented
Hi all, while this current version of the code seems to work very well as seen on Friday, I thought I'd increase `PITCH_MAX_RAD` in the `config.hpp` file to see issue https://github.com/QUB-ASL/bzzz/issues/24 is still happening, and unfortunately it is.
Any thoughts can we discuss under https://github.com/QUB-ASL/bzzz/issues/24

2023-05-04 11:48 UTC, alphaville commented on src/main.cpp
> +  // TODO create #define's with these parameters
Use `#define` for theses parameters

2023-05-04 11:49 UTC, alphaville commented on src/main.cpp
> +  float throttleFromRadio = radio.throttleReferencePercentage() * 1000 + 1000;
Use `#define` for theses parameters

2023-05-04 11:49 UTC, alphaville commented on src/radio.cpp
> +        int &radioThrottle,
Shall we remove this method?

2023-05-04 11:52 UTC, alphaville requested changes
Looks good, but have a look at a couple of comments I made. Before we merge this:

- do you want to address #26 now?
- what do you think about #25?

2023-05-04 15:25 UTC, alphaville commented
@jamie-54 since it flies, let's merge this into `main` and create a tag. Do you want to do some final changes first?

2023-05-04 16:14 UTC, jamie-54 commented
Hi I've just pushed the code that works and yea think we can merge it then tidy up the code and check that it still works thanks

2023-05-04 16:15 UTC, alphaville approved these changes
@jamie-54, very good - let's merge this now (first into `dev` and then `dev` into `main`) and we'll take it from there

2023-05-04 16:17 UTC, jamie-54 commented
ok

2023-05-04 16:17 UTC, merged