Create ESC_calibration.cpp
QUB-ASL/bzzz pull request #168
Opened 2023-12-01 12:03 UTC by Runway27

## Main Changes
This code is for calibrating the ESC
To calibrate the ESC copy and paste this into the `main.cpp` file and flash it to the ESP
## Associated Issues

- Closes #95 

## Tests

This has been tested as described above.

2023-12-01 12:05 UTC, jamie-54 approved these changes
Looks good to me

2023-12-01 12:24 UTC, alphaville requested changes
@Runway27 can you write some comments to explain what this test does? Also edit [this README file](https://github.com/QUB-ASL/bzzz/blob/main/hardware/tests/README.md) and provide a description of the test too.

2023-12-01 12:39 UTC, jamie-54 commented
@Runway27 update [this README](https://github.com/QUB-ASL/bzzz/tree/feature/95-ESC-calibration/hardware#readme) please and thank you

2023-12-01 15:25 UTC, alphaville commented on hardware/README.md
> +* 3 shot beeps and 1 long beep wou;ld confirm that the ESc is calibrated.
- shot -> short
- wou;ld confirm -> confirm
- ESc -> ESC

2023-12-01 15:31 UTC, alphaville commented
@Runway27 avoid editing the code directly on GitHub; install git on your computer and use the git client instead

2023-12-01 15:32 UTC, alphaville commented on hardware/ESC_calibration.cpp
> +    motorDriver.writeSpeedToEsc(2000, 2000, 2000, 2000); // Sets the signal to ESC as high
Avoid hard-coded values in the code

2023-12-01 15:34 UTC, Runway27 commented
> @Runway27 avoid editing the code directly on GitHub; install git on your computer and use the git client instead

For some reason I couldn't push to github on VS code.

2023-12-01 15:51 UTC, alphaville commented on hardware/ESC_calibration.cpp
> +#define High_Sgn 2000.
Such variables are `ALL_CAPS`

2023-12-05 02:20 UTC, alphaville approved these changes

2023-12-05 15:39 UTC, merged