Adding raspberry folder with the read_sbus folder and files for receiver
QUB-ASL/bzzz pull request #6
Opened 2023-04-10 12:40 UTC by jamie-54

Adding raspberry folder with the read_sbus folder and files for receiver

Some files might be removed at a later date.

2023-04-11 01:23 UTC, alphaville requested changes
Some of these files are from [`read_sbus`](https://github.com/VermontCoder/read_sbus). It would be a good idea to put these in a separate folder, that is, to separate our code from the library. If we don't need the file `read_sbus_from_GPIO_test.py` let's remove it.

Also:

- Update the README file with installation instructions
- Consider using a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for `read_sbus`
- Include some documentation

2023-04-17 10:21 UTC, alphaville commented on raspberry/read_sbus/README.md
> +
It's better to use a virtual environment. I've created one on our RPi and it seems to work OK.

2023-04-17 10:22 UTC, alphaville commented on raspberry/read_sbus/README.md
> +
Explain that we need to run the file [`read_sbus_from_GPIO_receiver.py`](https://github.com/QUB-ASL/bzzz/blob/feature/raspberry-readsbus/raspberry/read_sbus/read_sbus_from_GPIO_receiver.py)

2023-04-17 10:26 UTC, alphaville commented on raspberry/read_sbus/README.md
> +```
Combine these code blocks

2023-04-17 10:27 UTC, alphaville requested changes
It looks good. I've just made a few comments. We also need to read the values from the ESP. We can do this in a separate branch and PR.

2023-04-17 10:34 UTC, jamie-54 commented on raspberry/read_sbus/README.md
> +sudo apt-get install pigpio python-pigpio python3-pigpio. That can be installed as follows
Thought I fixed that sorry will do now

2023-04-17 18:20 UTC, alphaville commented on hardware/tests/hw_test_receiver.py
Apparently, this test needs to be placed in `raspberry/read_sbus` otherwise the file `read_sbus_from_GPIO.py` will not be accessible. The only alternative is to make a proper Python package. You can see how it's done in [OpEn](https://github.com/alphaville/optimization-engine/tree/master/open-codegen) - see the file `setup.py`.

However, I think it would be better to just move the test to `raspberry/read_sbus`. I'll create an issue and we can take care of this at a later stage.

2023-04-17 18:22 UTC, alphaville requested changes
@jamie-54 I think you just need to move the test to `raspberry/read_sbus` and then we can merge it.

2023-04-18 09:31 UTC, alphaville approved these changes

2023-04-18 11:09 UTC, merged