Added schematic and PCB design files for ESP shield.
QUB-ASL/bzzz pull request #67
Opened 2023-06-03 22:32 UTC by gunturiCM

## Main Changes
Added schematic and PCB design files. These files are the design files of a custom ESP32 shield board.
The shield has the MPU9250 IMU, ESCs, and buzzer circuit connections. All of the remaining free pins are brought out as separate ports for later use.

## Associated Issues

- Addresses #57

2023-06-03 22:33 UTC, gunturiCM commented
A separate push will be done for the Raspberry Pi shield.

2023-06-05 15:31 UTC, alphaville commented on design/PCBs/ESP_BOARD/Gerber_ESP_SHIELD_PCB_2023-06-03/How-to-order-PCB.txt
Change from `.txt` to `.md`

2023-06-05 15:32 UTC, alphaville requested changes
Can we have a figure file (PNG, preferably) with the new board?

2023-06-05 16:45 UTC, gunturiCM commented on design/PCBs/ESP_BOARD/Read_me.md
Done.

2023-06-05 16:45 UTC, gunturiCM commented on design/PCBs/ESP_BOARD/Gerber_ESP_SHIELD_PCB_2023-06-03/How-to-order-PCB.txt
Done.

2023-06-05 16:47 UTC, gunturiCM commented
> Can we have a figure file (PNG, preferably) with the new board?

I have included separate `*.png` files for the schematic, and PCB.

2023-06-06 08:17 UTC, jamie-54 commented
Should we not keep the PCB the same width as the Pi so they can stick together nicely and fit inside the case? Hoping to make the case smaller in future as well. Also think we would be better moving the  ESC header to a similar place as the old PCB just so we don't have to lengthen wires ect

2023-06-06 08:45 UTC, jamie-54 commented
@gunturiCM I made the changes I mentioned above can you check you are happy with them and update the PNG when you're happy

2023-06-06 19:51 UTC, gunturiCM commented
> @gunturiCM I made the changes I mentioned above can you check you are happy with them and update the PNG when you're happy

I see you have made the board compact. But my intention was to make the IMU be at the centre of the board (Like designing around the IMU, rather than designing around the ESP). I will take your submission as a reference to make the board more compact. Thanks!

2023-06-06 21:35 UTC, gunturiCM commented
> @gunturiCM I made the changes I mentioned above can you check you are happy with them and update the PNG when you're happy

@jamie-54 I have re-arranged the components according to your suggestions. Can you have a look and let me know if it needs any changes?

2023-06-08 21:44 UTC, gunturiCM commented
@jamie-54 I have changed the `ESC` headers position, please have a look and suggest any required modifications. Thanks.

2023-06-09 12:38 UTC, jamie-54 approved these changes
All looks good to me I've approved @gunturiCM @alphaville are you happy to merge?
Also think we should get one printed as son as possible

2023-06-13 11:16 UTC, gunturiCM commented
Added mounting holes. Please have a look.

2023-06-13 22:48 UTC, alphaville approved these changes
Looks good - thanks, Chandra

2023-06-14 20:08 UTC, merged