Changelog update
QUB-ASL/bzzz pull request #77
Opened 2023-06-13 15:31 UTC by gunturiCM

## Main Changes
Update the `CHANGELOG.md` file for `v0.2.0`.

2023-06-13 22:46 UTC, alphaville approved these changes

2023-06-13 22:51 UTC, alphaville requested changes
This is how a CHANGELOG file should look like: https://github.com/alphaville/optimization-engine/blob/master/CHANGELOG.md

2023-06-14 21:48 UTC, alphaville commented on raspberry/reference_position_tracker/position_tracker.py
This file doesn't belong here

2023-06-22 22:47 UTC, gunturiCM commented on raspberry/reference_position_tracker/position_tracker.py
Removed.

2023-06-23 22:26 UTC, alphaville approved these changes

2023-06-23 22:59 UTC, merged